[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "pillow>=11.3.0",
    "pytesseract>=0.3.13",
    "python-telegram-bot>=22.3",
    "telegram>=0.0.1",
]
